name: Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 24

    - name: Grant execute permission for mvnw
      run: chmod +x mvnw

    - name: Build with Maven
      run: ./mvnw -B package

    - name: Make staging directory
      run: mkdir staging

    - name: Copy JAR to staging
      run: cp target/*.jar staging

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
