name: Build snapshot and push to Maven

on:
  push:
    #branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    name: Build and Deploy Snapshot
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate secrets are available
        run: |
          if [ -z "${{ secrets.OSSRH_USERNAME }}" ]; then
            echo "ERROR: OSSRH_USERNAME secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.OSSRH_TOKEN }}" ]; then
            echo "ERROR: OSSRH_TOKEN secret is not set"
            exit 1
          fi
          echo "✅ Both OSSRH_USERNAME and OSSRH_TOKEN secrets are available"
          echo "Username length: ${#MAVEN_USERNAME}"
          echo "Token length: ${#MAVEN_PASSWORD}"
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}


      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 24
          server-id: sonatype-oss-snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Verify Maven settings
        run: |
          echo "Generated Maven settings.xml:"
          cat ~/.m2/settings.xml || echo "No settings.xml found"
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Test both old and new endpoints
        run: |
          echo "Testing OLD Sonatype endpoint..."
          curl -I -u "$MAVEN_USERNAME:$MAVEN_PASSWORD" \
            "https://oss.sonatype.org/content/repositories/snapshots/" \
            --fail-with-body || echo "❌ Old endpoint failed"
          
          echo ""
          echo "Testing NEW Sonatype endpoint..."
          curl -I -u "$MAVEN_USERNAME:$MAVEN_PASSWORD" \
            "https://s01.oss.sonatype.org/content/repositories/snapshots/" \
            --fail-with-body || echo "❌ New endpoint failed"
          
          echo ""
          echo "Testing login to Sonatype web interface..."
          curl -u "$MAVEN_USERNAME:$MAVEN_PASSWORD" \
            "https://s01.oss.sonatype.org/service/local/authentication/login" \
            --fail-with-body || echo "❌ Web login failed"
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

      - name: Build with Maven
        run: ./mvnw clean deploy -X
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}


